version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-alarms-notify
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes: []
    ports:
      - '5432:5432'

  alarm-service:
    build: .
    container_name: alarm-service
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3003:3003'
      - '4003:4003'
    volumes:
      - ./mqtt-certs:/app/mqtt-certs:ro
