version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-production-monitoring
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes: []
    ports:
      - '5433:5432'

  production-monitoring-service:
    build: .
    container_name: production-monitoring-service
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '3006:3006'
      - '4006:4006'
    volumes:
      - ./mqtt-certs:/app/mqtt-certs:ro
